mysql:
  username: "root"
  password: "0226"
  path: "127.0.0.1"
  port: "3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  dbname: "learnadmin"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
jwt:
  signing-key: da5295ca-49b6-492d-9fee-490c1af10534
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus